### ISSUE TITLE
Publish @dev version on npm

### ISSUE THREAD

**Issue by peterjah** [massalabs/massa-web3#102]
Following our practices in others massa repos (as, as-sdk...), it would be nice to have a "nightly publish" workflow to publish @dev versions on npm for each new commit on main.
It would allow us to use the latest features without having to wait for a release

**Comment by qdrn** [comment]
It was done here: https://github.com/massalabs/massa-web3/pull/103 right ?

**Comment by BatiGencho** [comment]
yep, I am closing this one.
