### ISSUE TITLE
Missing functions in js bundle

### ISSUE THREAD

**Issue by sebastien-forestier** [massalabs/massa-web3#105]
Some functions are missing in the js bundle, like `walletGenerateNewAccount`.

**Comment by BatiGencho** [comment]
@sebastien-forestier The method `walletGenerateNewAccount` is a static one, meaning that it needs to be accessed that way:

`window.massa.WalletClient.walletGenerateNewAccount(...)`

I can see it in my browser. Can you pls double-check again

**Comment by sebastien-forestier** [comment]
Thank you yes I see them that way!
