### ISSUE TITLE
args.serialize() is not recognized

### ISSUE THREAD

**Issue by nirnaeth-arnoediad** [massalabs/massa-web3#106]
When I hit send coin button on my example it returns args.serialize is not a function. Here is my code:
https://github.com/nirnaeth-arnoediad/massa-sc-examples/tree/main/send-coin
And here the output:
![FC1B2124-9FE6-4339-9045-3E66D1361F26](https://user-images.githubusercontent.com/57898835/220067107-2f95b712-302e-4d32-b8fa-97a2266ddf12.png)

**Comment by BatiGencho** [comment]
@nirnaeth-arnoediad Hi there .I think the problem is that you are overwriting you args in those two lines:
https://github.com/nirnaeth-arnoediad/massa-sc-examples/blob/main/send-coin/html/js/index.js#L31
https://github.com/nirnaeth-arnoediad/massa-sc-examples/blob/main/send-coin/html/js/index.js#L32

What you might want to do is something like this:

```
function initialize() {
  const massaArgs = new massa.Args();
  const inputAddress = document.getElementById("addr").value;
  massaArgs.addString(inputAddress);

  if (client) {
    client
      .smartContracts()
      .callSmartContract(
        {
          fee: 0,
          maxGas: 200000,
          targetAddress: sc_addr,
          targetFunction: "sendCoin",
          parameter: massaArgs.serialize(), // this is based on input arguments
        },
        baseAccount
      )
      .then((res) => {
        console.log(res);
      });
  }
}
```

**Comment by nirnaeth-arnoediad** [comment]
Hello @BatiGencho thanks for your answer. I made your suggested changes and now I have different error kindly please check. Thanks.
![image](https://user-images.githubusercontent.com/57898835/220391240-a93c668f-b633-4e06-b1cc-0d6cca894dba.png)

**Comment by Ben-Rey** [comment]
Is this issue still relevant ?
