### ISSUE TITLE
Update getDatastoreEntries method

### ISSUE THREAD

**Issue by lilyanB** [massalabs/massa-web3#112]
I would like to recover the data stored by the Smart Contract I deployed.
I looked at the doc here:
https://github.com/massalabs/massa-web3
```typescript
const datastoreEntries: Array<IContractStorageData> = await web3Client
    .publicApi()
    .getDatastoreEntries([
        {
            address: smartContractAddress,
            key: "some_key",
        } as IDatastoreEntry,
    ]);
```
with an example here:
https://github.com/massalabs/massa-blog/blob/2441a250564c17ef3004b4178186ef511b52f484/src/utils/sc-connect/articles.tsx#L25
```typescript
client.publicApi().getDatastoreEntries([{ address: sc_addr, key: 'N_BLOG_POSTS' }])
```
But it doesn't work.

Here is an example of what I have with Massa-web3 but I can't retrieve the data on my Smart Contract.
https://github.com/massalabs/massa-eth-bridge/blob/main/Massa/front/src/App.tsx#L172

``` typescript
  async function funcGetSwapinfo(swapID: string) {
    let args = new Args();
    args.addString(swapID);
    if (web3client && base_account) {
      const datastoreEntries: Array<IDatastoreEntry> = await web3client
        .publicApi()
        .getDatastoreEntries([
          {
            address: sc_addr,
            key: [0],
            //key: "swap1"
          } as IDatastoreEntryInput,
        ]);
      console.log(datastoreEntries[0])
      return(datastoreEntries)
    }
    return ('nothing')
  }
```

I think the doc is not update or I made a mistake?

**Comment by qdrn** [comment]
The example is probably outdated and using an older version of the massa-web3 library. Dis you check the documentation of massa-web3 ?

**Comment by lilyanB** [comment]
I checked at the documentation which is not update here: 
https://github.com/massalabs/massa-web3

But this doc is update:
https://web3.docs.massa.net/classes/PublicApiClient.html#getDatastoreEntries

I don't know how to get the information from my Smart Contrac

**Comment by lilyanB** [comment]
all works with this:
```typescript
var swapIDInBytes = Array.from(strToBytes(swapID))
const datastoreEntries: Array<IDatastoreEntry> = await web3client
        .publicApi()
        .getDatastoreEntries([
          {
            address: sc_addr,
            key: swapIDInBytes,
          } as IDatastoreEntryInput,
        ]);
```

**Comment by BatiGencho** [comment]
@lilyanB this is done in the latest v 1.15.0. I have also updated the docs. Cna you pls close it if all good with you ?

**Comment by lilyanB** [comment]
@BatiGencho yes, thanks for your help
