### ISSUE TITLE
New address format

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa-web3#117]
We added a new prefix in address to tell whether the address is an SC or User one. This change the string representation AND the bytes representation that will certainly break massa-web3 (byte representation used for compact bytes and sign) : 

- String format: A new character added in the prefix instead of A we have "AU" for user address or "AS" for smart contract address
- Byte format: We have a new byte at start of the bytes of the address which is 0 for user address and 1 for smart contract address

The `testnet_20` branch works well and have all this changes in it. You can run a sandbox node on it to benefit from the changes and test the changes on web3. If you have any questions on sandbox node or anything do not hesitate to ask.

**Comment by BatiGencho** [comment]
[https://github.com/massalabs/massa-web3/issues/117](url)
