### ISSUE TITLE
Webpack tune configs is blocking the use of Massa Web 3 outside of templates - Related with React Rewired

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/massa-web3#121]
The problem(s)
We can't import Massa Web3 into a frontend project which is not using WebPack

To Reproduce

Try to import Massa Web 3 in MassaTube or Thyra Home Page

Screenshots

Thyra version
latest as of today

Desktop (please complete the following information):

OS: NA
Google Chrome

Technical Details:

We remark we are using React Rewired with a tune config of Webpack. And we thinks it's directly related to this.

Our tool which is using esBuild instead of Webpack is not working with this. This is an example of future problems we will encounter

The main problem is not our case and using this with our tools but. We cannot provide a package only working with a specific Bundler. We should have an abstraction around this and provide a package working with any bundler

Needs : 

Create an abstraction to this. Users can't be impacted by the bundler this has to be transparent.
We need to upgrade the Webpack to have a generic bundle available to all frontends

**Comment by 0xMazout** [comment]
I have tested this : https://github.com/massalabs/vite-react-massa-starter

It's working with Massa Web 3. It unblock the development of Massa Tube and Vite projects

But after discussing with devs about it , we need to consider the fact : 
**that create template for each framework is not the right way to approach the problem.** 
And Massa Web3 needs to be easier to handle for builders and **abstract this tuning for each frameworks** . 

Massa Web3 need an update now or not, it's not my job to take a decision about this . 
My job is to alert on the point , actually it's a _"Big brake on the road"_  for the adoption . This is a long - mid term vision . But it's a need

FYI @SlnPons @gregLibert

**Comment by Ben-Rey** [comment]
https://github.com/massalabs/massa-web3/issues/221 should fix this

**Comment by SlnPons** [comment]
@gregLibert could you help to test this issue please?
