### ISSUE TITLE
Improving TypeDoc documentation

### ISSUE THREAD

**Issue by leoloco** [massalabs/massa-web3#122]
When developing a decentralized application on Massa, I often rely on the auto-generated TypeDoc. The problem is I find it difficult to navigate in.
 
The instructions and examples on the landing page are great and it gets you starting fast. However, this landing page does not cover all the use cases, which is normal. Thus I often have to navigate trough the various class, methods, and interfaces listed on the right banner.

I find it very difficult to navigate and find what you need in this list; For example, when I see an interface that looks useful for my use case, I would like to know which methods implement it and which other ones return it. 

Wouldn't it be possible to set typeDoc to do something like that ? 

Other example, would it be possible for the right banner to display all the methods implemented by each class ? 

Overall the typeDoc documentation covers all the code but there should be more links between the different pages

**Comment by qdrn** [comment]
I think you worked on the doc @Thykof so you might have an answer as well.

**Comment by Thykof** [comment]
Thanks @leoloco for you feedback.

Let's have a look at https://typedoc.org/guides/plugins/ to search for a plugin that can automatically link interfaces and classes.

Also in the code we can write ` * @see {@link classThatImplementsThisInterface}` in the typedoc of an interface.

**Comment by leoloco** [comment]
I haven't found a plugin that matches our needs. But from the research I've made, it seems that the second solution you suggest could do the trick.

**Comment by Thykof** [comment]
here is an example of a see/link in the massa-as-sdk https://github.com/massalabs/massa-as-sdk/blob/main/assembly/std/index.ts#L462
