### ISSUE TITLE
Error initializing massa-web3 script

### ISSUE THREAD

**Issue by nirnaeth-arnoediad** [massalabs/massa-web3#123]
I have a simple html code to connect massa web3 but when I load the webpage an error kicks in. I leave the screenshot of the error at bottom. Here my html code:
```
<!DOCTYPE html>
<html>
    <head>
        <title>Send Coin</title>
    </head>
    <body>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@massalabs/massa-web3@1.15.1/bundle.js"></script>
        <script>
            console.log("Massa Web3 ", window.massa);
        </script>
        <script src="js/index.js"></script>
        <label for="addr">Wallet Address to Send Coin:</label><br />
        <input type="text" id="addr" name="addr" size="50" /><br />
        <button onclick="initialize();">Send Coin</button>
    </body>
</html>
```
Here Screenshot of the error:

![html](https://user-images.githubusercontent.com/57898835/223662325-de81cdcf-076e-4388-825c-919a98cb5a46.png)

**Comment by BatiGencho** [comment]
Hey, not sure what that means to be honest, can you check with the latest released version, please. (v.1.16.1)

**Comment by Ben-Rey** [comment]
Is this issue still relevant ?

**Comment by Ben-Rey** [comment]
Is this issue still relevant ?
