### ISSUE TITLE
Arrays of strings, u64 and i64

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-web3#127]
Current version of Args in AssemblyScript allows serialization of various types.

However, we need a way to serialize and deserialize arrays of strings, u64, and i64 in an Args-compatible format in JavaScript. 

>__Note:__ This feature is not intended to provide the same level of flexibility as in AssemblyScript.

Strings can be encoded in either UTF8 or UTF16, but the encoding format should be explicit so that end-users can perform conversions if necessary.

**Comment by BatiGencho** [comment]
Already resolved and merged into main.
