### ISSUE TITLE
Implement a web3 client factory method that connects with wallet-provider's providers

### ISSUE THREAD

**Issue by BatiGencho** [massalabs/massa-web3#129]
It is suggested to have massa-web3 extended with a new factory method for initializing a client that connects to the wallet providers in the `wallet-provider` library. 

A pseudocode for the method will look like this:

```typescript
ClientFactory.createClientFromProviders() {
    // method will be calling getNodeUrls() from the `wallet-provider`
}
```
where the ClientFactory 's new method createClientFromProviders will be from the massa-web3 and the getNodeUrls from the wallet-provider. Inside we should implement a mechanism which will be recursively calling the getNodeUrls every now and then and if new providers are found adding them to massa-web3's providers list. Something similar has already been done with the ThyraWalletDiscovery in the wallet-provider.

**Comment by Ben-Rey** [comment]
@gregLibert Do we still need this ?

**Comment by gregLibert** [comment]
We do. But it was implemented, no ?
