### ISSUE TITLE
Detect the presence of `massa-wallet` (and use it if present)

### ISSUE THREAD

**Issue by yvan-sraka** [massalabs/massa-web3#13]
We should check in browser if `window.massa` exist, and in this case, to use the `Wallet` [`signContent(transaction)`](https://github.com/massalabs/massa-wallet/blob/main/massa/Wallet.js#L62-L79) function to sign operations.

**N.B.** be aware since last version, [`Network`](https://github.com/massalabs/massa-wallet/blob/main/massa/Network.js) rely on `massa-web3` to communicate with a `massa-node`!

**Comment by yvan-sraka** [comment]
`window.web3` is maybe not the right way to do it … `window.postMessage()` is another way to do it, what do you think about it?

**Comment by BatiGencho** [comment]
This issue is not relevant anymore and has been resolved long time ago. I am closing it.

**Comment by BatiGencho** [comment]
This issue is not relevant anymore and has been resolved long time ago. I am closing it.
