### ISSUE TITLE
Make sendJsonRPCRequest public

### ISSUE THREAD

**Issue by leoloco** [massalabs/massa-web3#136]
In this [issue](https://github.com/massalabs/massa-web3/issues/135), it is mentioned that it would be nice if we could use an external account (for example, an account stored in a browser extension wallet), to sign transactions. At the moment, there is no wallet in the Massa ecosystem that implements the [massa standard](https://github.com/massalabs/massa-standards/blob/main/wallet/dapps-communication.md) or that supports the last version of massa-web3. Thus, at the moment, it is not possible to send a transaction that was not signed with massa-web3 `baseAccount`. 
Making the sendJsonRPCRequest public would solve this problem, as plugin wallets such as Bearby already support signing arbitrary data. 
Would it be possible to make sendJsonRPCRequest public or does it have some implications I did not think about?

**Comment by qdrn** [comment]
It could be either `sendJsonRPCRequest` or `sendOperation`.

**Comment by gregLibert** [comment]
We should do that in a clean way. @SlnPons can you tell me if this endpoint exist ?

**Comment by Ben-Rey** [comment]
@gregLibert Is it still relevant or will it be fixed by wallet provider ?
