### ISSUE TITLE
add ci for the websockets example

### ISSUE THREAD

**Issue by Elli610** [massalabs/massa-web3#143]

**Comment by Ben-Rey** [comment]
@gregLibert does the websockets will still be used ?

**Comment by gregLibert** [comment]
> @gregLibert does the websockets will still be used ?

No, i don't think so. We need to synch with @aoudiamoncef to be sure.

**Comment by aoudiamoncef** [comment]
Hello 👋 

WebSockets are deprecated ⚠️ 

We are moving to gRPC

More info in https://docs.massa.net/en/latest/technical-doc/grpc.html

**Comment by aoudiamoncef** [comment]
> > Hello wave
> > WebSockets are deprecated warning
> > We are moving to gRPC
> > More info in [docs.massa.net/en/latest/technical-doc/grpc.html](https://docs.massa.net/en/latest/technical-doc/grpc.html)
> 
> What is the plan to support the browser? Do you plan to propose an proxy ?

Sorry, I didn't see this message. 

We tried to explore the [Json transcoding](https://github.com/hyperium/tonic/blob/master/examples/src/json-codec/common.rs) in server side but this will make gRPC API complex. 

Currently, we added gRPC gateway annotation to make proxing easier.
