### ISSUE TITLE
Generate and host a browserify version of the package

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa-web3#17]
To generate a browserify version : `browserify dist/index.js --standalone massa > bundle.js` .

We can also uglify it to get a ligther version : `uglifyjs bundle.js > bundle-minified.js`

This should be created by the CI and upload in a server also.

**Comment by AurelienFT** [comment]
No the dist is not enough. We can use uglify or minify. Could be great to add on the CI on release. @BatiGencho

**Comment by qdrn** [comment]
Done in https://github.com/massalabs/massa-web3/pull/38. Closing.
