### ISSUE TITLE
retryStrategyOn not implemented in clientFactory

### ISSUE THREAD

**Issue by julienbrs** [massalabs/massa-web3#293]
in [ClientFactory.ts](https://github.com/massalabs/massa-web3/blob/8a0801f97ab8d222236a80e80164b3ae3c4bb985/src/web3/ClientFactory.ts#LL63C5-L63C10), there is a parameter `retryStrategyOn` for the constructor of a `Client`:
```
const client: Client = new Client(
      {
        retryStrategyOn,
        providers,
      } as IClientConfig,
      baseAccount,
    );
```
However, it seems that this parameter has no consequences in the `Client` class, should it be implemented or removed ?

**Comment by c1tt1** [comment]
That parameter isn't necessarily used in the [ClientFactory.ts](https://github.com/massalabs/massa-web3/blob/8a0801f97ab8d222236a80e80164b3ae3c4bb985/src/web3/ClientFactory.ts#LL63C5-L63C10), but actually being [passed](https://github.com/massalabs/massa-web3/blob/8a0801f97ab8d222236a80e80164b3ae3c4bb985/src/web3/Client.ts#L31) to both [PrivateApiClient.ts](https://github.com/massalabs/massa-web3/blob/8a0801f97ab8d222236a80e80164b3ae3c4bb985/src/web3/PrivateApiClient.ts) and [PublicApiClient.ts](https://github.com/massalabs/massa-web3/blob/8a0801f97ab8d222236a80e80164b3ae3c4bb985/src/web3/PublicApiClient.ts).

Both Api clients only use it for retry purposes, so I would assume the question should be if the retry be implemented in [ClientFactory.ts](https://github.com/massalabs/massa-web3/blob/8a0801f97ab8d222236a80e80164b3ae3c4bb985/src/web3/ClientFactory.ts)
