### ISSUE TITLE
Fix typos in README

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-web3#3]
There's a typo in the description for smart-contract compilation, something is missing:
"Massa sdk provides methods for compiling smart contracts written in Assemblyscript with Typescript either via cli or on the fly. **If on the fly With both methods**, the returned values are a text and a binary representations of the wasm."

**Comment by BatiGencho** [comment]
not relevant anymore as I have moved and fixed these info to the mass-sc-utils.
