### ISSUE TITLE
Args for array of string: elements limited to 100 bytes 

### ISSUE THREAD

**Issue by peterjah** [massalabs/massa-web3#306]
When serializing an array of string, the size of each element is hardcoded to 100bytes (=1OO chars in utf8)
Its mean that even if the string element is shorter, we always use 100 bytes per elements of the array.
This is not optimal.
I also open the discussion to know where this limitation comes from, because 100 bytes is quite restrictive.

To fix this, we must change the way of serializing/deserializing array of string in as-types and change massa-web3 according it.
My recommendation would be to serialize string elements like we do in Args for simple string: we use the 4 first bytes to put the string length in i32, and then the string serialized

**Comment by c1tt1** [comment]
@peterjah could you please provide some examples? or snippets?
