### ISSUE TITLE
instanceof Args not working

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/massa-web3#327]
It seems that the usage of ```instanceof Args```  within the wallet provider codebase is causing an issue during the compilation process.

## To reproduce

Use ```instanceof Args``` in the wallet provider project and ```npm run build``` (The Args class from massa-web3)

**Comment by c1tt1** [comment]
`@massalabs/as-types` is an assemblyscript module and calling `instanceof Args` must be in an assemblyscript project, like in this [setup](https://www.assemblyscript.org/getting-started.html#setting-up-a-new-project)

ex.
`index.ts`
```js
// The entry file of your WebAssembly module.

import { Args } from '@massalabs/as-types';

const keyBaseArgs = new Args();

export const inst = (keyBaseArgs instanceof Args).toString();
```
`index.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
<script type="module">
import { inst } from "./build/release.js";
document.body.innerText = inst.valueOf();
</script>
</head>
<body></body>
</html>
```

The served html will be:
![image](https://github.com/massalabs/massa-web3/assets/21057231/d0741745-be84-45eb-8152-e098fed5b7c5)

**Comment by Ben-Rey** [comment]
> `@massalabs/as-types` is an assemblyscript module and calling `instanceof Args` must be in an assemblyscript project, like in this [setup](https://www.assemblyscript.org/getting-started.html#setting-up-a-new-project)
> 
> ex. `index.ts`
> 
> ```js
> // The entry file of your WebAssembly module.
> 
> import { Args } from '@massalabs/as-types';
> 
> const keyBaseArgs = new Args();
> 
> export const inst = (keyBaseArgs instanceof Args).toString();
> ```
> 
> `index.html`
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
> <script type="module">
> import { inst } from "./build/release.js";
> document.body.innerText = inst.valueOf();
> </script>
> </head>
> <body></body>
> </html>
> ```
> 
> The served html will be: ![image](https://user-images.githubusercontent.com/21057231/248576139-d0741745-be84-45eb-8152-e098fed5b7c5.png)

Thanks for your comment, but I was referring to Args in massa-web3, which is a typecript object.
@Elli610

**Comment by Elli610** [comment]
If you want to test easily, you just need to replace this part
`
    if (parameter instanceof Uint8Array) {
      argumentArray = Array.from(parameter);
    } else {
      argumentArray = Array.from(parameter.serialize());
    }
`
by this
`
    if (parameter instanceof Args) {
      argumentArray = Array.from(parameter.serialize());
    } else {
      argumentArray = Array.from(parameter);
    }
`

here: https://github.com/massalabs/wallet-provider/blob/main/src/massaStation/MassaStationAccount.ts#L346-L350C6

Then, if you run "npm run build", it shoul throw something like this : https://github.com/massalabs/wallet-provider/actions/runs/5343251032/jobs/9686088499
