### ISSUE TITLE
Error when trying to do a callSmartContract from the front

### ISSUE THREAD

**Issue by jimmylies** [massalabs/massa-web3#33]
I get this error when I try to do a callSmartContract from the front:
![error](https://user-images.githubusercontent.com/95318479/183398811-b214d651-693a-47f4-beee-371777d98aeb.png)

Apparently the problem comes from massa-web3, I tried with all versions since 1.9.8 but I always have the same error. For the version of the node I am connected the version 12 of the innonet.

**Comment by BatiGencho** [comment]
@jimmylies also, where does it occur- labnet, testnet or a local node ?

**Comment by jimmylies** [comment]
I fixed it by setting correctly the default client.
