### ISSUE TITLE
Reduce size of library

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-web3#41]
The size of the library/bundle is a recurring issue.

Maybe something we can do first is split the library in several sub libraries. This would allow users to use only the relevant part for their use case.

**Comment by qdrn** [comment]
cc @Eitu33

**Comment by qdrn** [comment]
Maybe split the library logic for API calls from the wallet logic ?

cc @AurelienFT

**Comment by AurelienFT** [comment]
Yes it's a good idea we could also split API of node from SC

**Comment by BatiGencho** [comment]
I think there are a few things we could do straightaway. When I designed the lib I made it compasable meaning that we now have so-called Clients (public, private, wallet, sc, vault) which could be immediately put into their own modules. Ethereum web3 does it same way: they have web3-core, web3-accounts, web3-wallets, web3-utils etc.

**Comment by Ben-Rey** [comment]
Done with web3-next
