### ISSUE TITLE
Allow read only calls without a connected account

### ISSUE THREAD

**Issue by leoloco** [massalabs/massa-web3#412]
**Context**
Currently, it seems like to perform any type of call to a smart contract, rather it be a read or a write, it is required to have an account connected. This is quite inconvenient when it comes to building frontends. 

**Need**
Add all the methods of [massa json rpc](https://playground.open-rpc.org/?schemaUrl=https://test.massa.net/api/v2&uiSchema[appBar][ui:input]=false&uiSchema[appBar][ui:inputPlaceholder]=Enter+Massa+JSON-RPC+server+URL&uiSchema[appBar][ui:logoUrl]=https://massa.net/favicons/favicon.ico&uiSchema[appBar][ui:splitView]=false&uiSchema[appBar][ui:darkMode]=false&uiSchema[appBar][ui:title]=Massa&uiSchema[appBar][ui:examplesDropdown]=false&uiSchema[methods][ui:defaultExpanded]=false&uiSchema[methods][ui:methodPlugins]=true&uiSchema[params][ui:defaultExpanded]=false) to massa web3. 

If the method in the rpc does not require an account, then the method exposed by massa web3 shouldn't either.

**Comment by leoloco** [comment]
We could rely on the JSON rpc API to execute readOnlyCalls on smart contracts and thus build frontends. But the web3 community is not used to this. They are used to have a single point of entry to the blockchain under the form of a web3 library. 
I think that implementing this issue would greatly reduce the perceived complexity of Massa products

**Comment by qdrn** [comment]
Part of a bigger issue: https://github.com/massalabs/massa-web3/issues/44
