### ISSUE TITLE
Change nextU8 return type

### ISSUE THREAD

**Issue by leoloco** [massalabs/massa-web3#422]
**Context**
In this [file](https://github.com/massalabs/massa-web3/blob/main/src/utils/arguments.ts) the return type of the nextU8 method is bigInt. 
I'm unsure if it was intentional but it seems kind of odd that nextU8 return a bigint when nextU32 returns a type number.

**Comment by Ben-Rey** [comment]
Moved here https://github.com/massalabs/web3-utils/issues/5
