### ISSUE TITLE
Clean library of unused functions/interfaces

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-web3#43]
There are some things that are currently not used at all (e.g. https://github.com/massalabs/massa-web3/blob/main/src/interfaces/IClique.ts). It would be nice at some point to clean the code.

**Comment by BatiGencho** [comment]
@qdrn The IClique is currently indeed being used in the func:

	`getCliques(): Promise<Array<IClique>>;`
	
You can also see its impl in the public api.

**Comment by qdrn** [comment]
If you believe there is nothing that is not up to date we can close the issue.

**Comment by BatiGencho** [comment]
@qdrn wait, if its removed from the massa-client (rust) does it mean the rpc endpoint got removed or is it still there, but no longer in the rust client? I am confused

**Comment by qdrn** [comment]
> @qdrn wait, if its removed from the massa-client (rust) does it mean the rpc endpoint got removed or is it still there, but no longer in the rust client? I am confused

It's still there but not in the rust client!
