### ISSUE TITLE
core-js deprecated

### ISSUE THREAD

**Issue by julienbrs** [massalabs/massa-web3#436]
Core-js deprecated appears again, same old issue as https://github.com/massalabs/massa-web3/issues/235
Now this warning appears because of the import of wallet-provider, however wallet-provider uses esmify  (which is the package using core-js deprecated), so we can't remove it from dependencies, and  esmify hasn't been updated for 5 years now.
Solution could be to not rely on esmify anymore in wallet-provider

**Comment by Ben-Rey** [comment]
Done here: https://github.com/massalabs/wallet-provider/issues/96
