### ISSUE TITLE
Remove `baseAccount` constraint from client creation

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-web3#44]
I find it weird to have to define an account to make API calls. For many use cases you will never define an account (for instance if you want to build an explorer). Also in some cases the account will be handled by something else (browser extension or Thyra). It would probably make sense to make it optional or rework the code so that it's passed as a parameter to the relevant methods.

WDYT ?

cc @AurelienFT @Eitu33

**Comment by qdrn** [comment]
Seems to be optional but I find it counter intuitive that it's (afaik) initialized for us if we don't put it in the first place.

**Comment by AurelienFT** [comment]
Yes that's a good idea we should be able to make calls without account but it's cool that calls that need an address, and therefore a account, are under the account (or sub properties) object so that you understand that you need an account.

**Comment by BatiGencho** [comment]
@qdrn  Do we still need this issue or can we close it ? I believe the baseAccount is there for the reasons @AurelienFT  has mentioned and other web3 clients also seem to have that.

**Comment by BatiGencho** [comment]
@qdrn @AurelienFT Guys, if we are keeping it, I guess we could just close the  issue. To me, it is a design pattern that is being used in pretty much all web3 clients out there.

**Comment by AurelienFT** [comment]
I think it's cool that API calls that don't need `baseAccount` can work without. Just I don't think it needs to be done right now but letting the issue open is a good way to not forget.

**Comment by qdrn** [comment]
It makes sense for people that want to build an explorer for instance so I would keep the issue but not necessarily fix it right away.

**Comment by Ben-Rey** [comment]
I will close this one as we can do
```typescript
    const client: Client = await ClientFactory.createDefaultClient(
      DefaultProviderUrls.BUILDNET,
      CHAIN_ID.BuildNet
    );
```
