### ISSUE TITLE
.awaitRequiredOperationStatus cannot await on both speculative status

### ISSUE THREAD

**Issue by sydhds** [massalabs/massa-web3#472]
Cannot await on both:
* EOperationStatus.SPECULATIVE_SUCCESS
* EOperationStatus.SPECULATIVE_ERROR

**Comment by Ben-Rey** [comment]
@gregLibert We can start the discussion here.

**Comment by damip** [comment]
From what I understand, this is heavily impairing the developer experience and should be solved asap.

**Comment by Ben-Rey** [comment]
One quick solution would be to accept an array of status and return if one of them is reached.

**Comment by gregLibert** [comment]
Let's focus on building something robust.
IMHO we should go to something like event manager.
We could also wrap the event management using the [observable design pattern](https://refactoring.guru/design-patterns/observer/typescript/example) for a specific operation.

@damip we should also discuss about the priority, ASAP is misleading I think.

**Comment by damip** [comment]
Here is a preliminary specification on how to make things cleanly:

After emitting an operation:
* wait for the operation to be executed as speculative, notify of the result (notification can happen 0, 1 or multiple times if the status changes)
* wait for the operation to be executed as final, notify of the result (can happen 0 or 1 times)
  * in that case, stop waiting, we are done
* if the final execution cursor becomes superior or equal to the operation's expiry period, return that the execution did not happen
  * in that case, stop waiting, we are done

**Comment by Ben-Rey** [comment]
> Cannot await on both:
> 
> * EOperationStatus.SPECULATIVE_SUCCESS
> * EOperationStatus.SPECULATIVE_ERROR

Just for information. We can do that 

```typescript
    try {
      const specSuccess = client
        .smartContracts()
        .awaitRequiredOperationStatus(opId, EOperationStatus.SPECULATIVE_SUCCESS);

      const specError = client
        .smartContracts()
        .awaitRequiredOperationStatus(opId, EOperationStatus.FINAL_ERROR);

      const finalSuccess = client
        .smartContracts()
        .awaitRequiredOperationStatus(opId, EOperationStatus.FINAL_SUCCESS);

      const finalError = client
        .smartContracts()
        .awaitRequiredOperationStatus(opId, EOperationStatus.FINAL_ERROR);

      const specResult = await Promise.race([specSuccess, specError]);
      console.log(EOperationStatus[specResult]);

      const finalResult = await Promise.race([finalSuccess, finalError]);
      console.log(EOperationStatus[finalResult]);
    } catch (error) {
      console.error("An error occurred:", error);
    }
    ```
