### ISSUE TITLE
Add Args class to serialize arguments into bytes (u32, string)

### ISSUE THREAD

**Issue by Thykof** [massalabs/massa-web3#50]
*related to <https://github.com/massalabs/massa-as-sdk/issues/16>*

In order to call a SC that use the assembly script Args class for de-serialize arguments, massa-web3 library needs a way to make the serialization.

See assembly script Args class here: https://github.com/massalabs/massa-as-sdk/blob/main/assembly/std/arguments.ts

There is a draft of an Args class in javascript here: https://github.com/massalabs/massa-dapp-example-sum/blob/c6d744f172975b93ccd850300e764cb1f948588a/src/arguments.js

**Job to be done in this task**

add an Args class in typescript.

Types that the Args class ultimately needs to handle:
- [x] u32
- [ ] i32
- [ ] f32
- [ ] u64
- [ ] i64
- [ ] f64
- [x] string
- [ ] array of bytes

for each types, add `add` and `next` methods.

**Scope of this issue**
- [x] string
- [x] u32

Feel free to create new issue to work on a specific type.

**Comment by BatiGencho** [comment]
@Thykof @qdrn  We already have a nice method to serialize jey-value args in the https://github.com/massalabs/massa-web3/blob/main/src/web3/BaseClient.ts#L178

**Comment by Thykof** [comment]
The massa-as-sdk now has a way to serialized data from/to bytes, so we need a way to do the same in javascript for calling smart contract. Greg and I have started something here: https://github.com/massalabs/massa-dapp-example-sum/blob/master/src/arguments.js

**Comment by gregLibert** [comment]
> @Thykof @qdrn We already have a nice method to serialize jey-value args in the https://github.com/massalabs/massa-web3/blob/main/src/web3/BaseClient.ts#L178

Im' not sur it's not the same scope :  here we are talking about serailizing data to send to a SC in a binary format instead of JSON one.
