### ISSUE TITLE
Add coins parameter to readSmartContract

### ISSUE THREAD

**Issue by Thykof** [massalabs/massa-web3#506]
The coins parameter in the execute_read_only_call is important to simulate correctly the call, especially when we are not reading a value in the smart contract, but doing a dry run of a call to a function (to estimate de gas cost for example).

The coins parameter must be in MAS, in string representation. Example: `coins":"1"` is 1 MAS sent.

**Comment by Ben-Rey** [comment]
@Thykof Can we close this one ?
