### ISSUE TITLE
Make deploy arguments optional and add default values

### ISSUE THREAD

**Issue by peterjah** [massalabs/massa-web3#51]
in `smartContracts().deploySmartContract(`

the following arguments may be optional, 
        fee: 0,
        maxGas: 2000000,
        gasPrice: 0,
        coins: 0,
If not provided, the above default values should be used

**Comment by qdrn** [comment]
Why would you want to do that ?

**Comment by BatiGencho** [comment]
It might not be a bad idea. wdyt @qdrn  ?

**Comment by qdrn** [comment]
Right now it's ok but in the longer term it will start costing money to upload SC so I'm reluctant to put a high default value. We could put high gas and zero gas price/fee but chances are that the SC will not be deployed so it might end up confusing.

**Comment by BatiGencho** [comment]
@qdrn So what is your verdict for this issue - do we make any defaults at all at the moment or do we close the issue for now ?

**Comment by qdrn** [comment]
@peterjah why can't you put the default parameter in your application ? What's your opinion ?

**Comment by BatiGencho** [comment]
@peterjah @qdrn Can we close this issue ?
