### ISSUE TITLE
Npm run test doesn't work on Windows

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/massa-web3#53]
When I run the command 'npm run test' I get the following error :

'TS_NODE_COMPILER_OPTIONS' is not recognized as an internal command

The solution is to remove "TS_NODE_COMPILER_OPTIONS='{\"module\":\"commonjs\"}'" from the package.json.

This make the tests work on both windows and macOS.

**Comment by Thykof** [comment]
Solved by https://github.com/massalabs/massa-web3/pull/57
