### ISSUE TITLE
Varint is intrinsically part of the serialization and deserialization logic. If we want to offer abstraction, the part that should be abstracted should be the `Canonicalizer` (canonicalization operation including `canonicalize` and `uncanonicalization`, if that makes sense from a code usability perspective).

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa-web3#565]
Varint is intrinsically part of the serialization and deserialization logic. If we want to offer abstraction, the part that should be abstracted should be the `Canonicalizer` (canonicalization operation including `canonicalize` and `uncanonicalization`, if that makes sense from a code usability perspective).

_Originally posted by @gregLibert in https://github.com/massalabs/massa-web3/pull/559#discussion_r1574562505_

**Comment by gregLibert** [comment]
Duplicate of #564
