### ISSUE TITLE
Better referencement of the documentation

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa-web3#63]
The documentation on the readme of this repository is good and have a lot of details but during our last hackathon at GGH participants had an hard time finding it and so didn't think it was existing.

**Comment by AurelienFT** [comment]
Yes also. We must be more clear on where to find the bundles and it will be even better if we have a CDN.

**Comment by qdrn** [comment]
I've clarified that we have bundles in the release page. I think better referencing should be done in @massalabs/massa-docs.
