### ISSUE TITLE
third optional argument of ClientFactory.createDefaultClient isn't optional in the code

### ISSUE THREAD

**Issue by adassoul** [massalabs/massa-web3#76]
fn def
![image](https://user-images.githubusercontent.com/47633088/205508061-58a6dcbe-5370-4054-afc7-2af07e13d15a.png)

example in readme
![image](https://user-images.githubusercontent.com/47633088/205508109-4c6d4203-6f51-4157-a90b-1208429302c1.png)

as we can see : 
- in the function definition, we have 3 args : provider, retryStrategyOn and baseAccount
- and in the readme.md example, we are using only 2 args : the first and the third arguments from the function definition (provider and baseAccount)
-> which, in practice, when we follow the example, baseAccount is compiled as being retryStrategyOn and baseAccount is undefined (cf following image) even if it's a none mandatory arg.

![image](https://user-images.githubusercontent.com/47633088/205509716-b0e7b4ab-2062-49a4-a796-7b7abcbaad0b.png)
![image](https://user-images.githubusercontent.com/47633088/205509721-69c856d4-90d3-4353-848b-b7da8615dced.png)
![image](https://user-images.githubusercontent.com/47633088/205509728-57667165-db57-4024-a8d2-2b04c51707d9.png)

**Comment by BatiGencho** [comment]
Hi @adassoul , 

well spotted thanks. It should be fixed in this MR: https://github.com/massalabs/massa-web3/pull/77 which I will merge in soon. Thank you for drawing our attention to this!

**Comment by BatiGencho** [comment]
Hi @adassoul 

The readme has been fixed and I have published a new version 1.11.1 with the updated readme. Thanks for your help!
