### ISSUE TITLE
massa-web3 integration bundle in html files typo : tag not closed

### ISSUE THREAD

**Issue by adassoul** [massalabs/massa-web3#79]
Hello,
In the README.md file, there is a typo : 
`<script type='text/javascript' src="https://cdn.jsdelivr.net/npm/@massalabs/massa-web3@x.x.x/bundle.js"</script>`
should be 
`<script type='text/javascript' src="https://cdn.jsdelivr.net/npm/@massalabs/massa-web3@x.x.x/bundle.js"></script>`
Nothing crazy :)

**Comment by BatiGencho** [comment]
I have fixed this tiny typo and merged to main. Next release will have an improved docs. If you wish, you can close the ticket @adassoul . Thanks for your comment

**Comment by qdrn** [comment]
Closing as there hasn't been activity for several weeks.
