### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-web3#8]

**Comment by damip** [comment]
This seems to be a recurring issue. 
I think we should either automate this somehow, or use the github repo directly

**Comment by qdrn** [comment]
> This seems to be a recurring issue. I think we should either automate this somehow, or use the github repo directly without NPM

I don't understand your point. This repo is not on NPM. That's the purpose of this issue.

**Comment by damip** [comment]
> > This seems to be a recurring issue. I think we should either automate this somehow, or use the github repo directly without NPM
> 
> I don't understand your point. This repo is not on NPM. That's the purpose of this issue.

oh ok, I thought it was related to keeping the NPM side in sync with the github side. The issue didn't offer much details :p

**Comment by yvan-sraka** [comment]
It's already published here yes https://www.npmjs.com/package/massa-web3
