### ISSUE TITLE
TypeDoc deploy - massa web3

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/massa-web3#90]

**Comment by 0xMazout** [comment]
Discussion directly linked to this : https://github.com/massalabs/massa-web3/issues/85#issuecomment-1377449288

just to not lost info : blocked by @BatiGencho action to update TypeDoc .

Will go through this when typedoc is ready

**Comment by longgamma-massa** [comment]
@BatiGencho this link to documentation from the Readme doesn't work:
![Image](https://user-images.githubusercontent.com/113043914/219315649-3d7301d8-8474-4440-aee2-6ec13b02cd27.png)

**Comment by qdrn** [comment]
Fixed, closing.
